site_name: Citrix Federated Authentication Service 1906 PowerShell cmdlets
site_description: Citrix Federated Authentication Service 1906 PowerShell cmdlets Reference
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - meta

pages:
- Citrix Federated Authentication Service PowerShell cmdlets:
    - Introduction: index.md
- cmdlets reference:
  - Get-FasAdministrationPolicy: Get-FasAdministrationPolicy.md
  - Get-FasAuthorizationCertificate: Get-FasAuthorizationCertificate.md
  - Get-FasCertificateDefinition: Get-FasCertificateDefinition.md
  - Get-FasMsCertificateAuthority: Get-FasMsCertificateAuthority.md
  - Get-FasMsTemplate: Get-FasMsTemplate.md
  - Get-FasPolicyOid: Get-FasPolicyOid.md
  - Get-FasPrivateKeyPoolInfo: Get-FasPrivateKeyPoolInfo.md
  - Get-FasRule: Get-FasRule.md
  - Get-FasServer: Get-FasServer.md
  - Get-FasServerForUser: Get-FasServerForUser.md
  - Get-FasUserCertificate: Get-FasUserCertificate.md
  - Import-FasAuthorizationCertificateResponse: Import-FasAuthorizationCertificateResponse.md
  - New-FasAuthorizationCertificate: New-FasAuthorizationCertificate.md
  - New-FasAuthorizationCertificateRequest: New-FasAuthorizationCertificateRequest.md
  - New-FasCertificateDefinition: New-FasCertificateDefinition.md
  - New-FasMsTemplate: New-FasMsTemplate.md
  - New-FasPolicyOid: New-FasPolicyOid.md
  - New-FasRule: New-FasRule.md
  - New-FasUserCertificate: New-FasUserCertificate.md
  - Publish-FasMsTemplate: Publish-FasMsTemplate.md
  - Remove-FasAuthorizationCertificate: Remove-FasAuthorizationCertificate.md
  - Remove-FasCertificateDefinition: Remove-FasCertificateDefinition.md
  - Remove-FasMsTemplate: Remove-FasMsTemplate.md
  - Remove-FasPolicyOid: Remove-FasPolicyOid.md
  - Remove-FasRule: Remove-FasRule.md
  - Remove-FasUserCertificate: Remove-FasUserCertificate.md
  - Set-FasAdministrationPolicy: Set-FasAdministrationPolicy.md
  - Set-FasCertificateDefinition: Set-FasCertificateDefinition.md
  - Set-FasPolicyOid: Set-FasPolicyOid.md
  - Set-FasRule: Set-FasRule.md
  - Set-FasServer: Set-FasServer.md
  - Test-FasCertificateSigningRequest: Test-FasCertificateSigningRequest.md
  - Test-FasCrypto: Test-FasCrypto.md
  - Test-FasKeyPairCreation: Test-FasKeyPairCreation.md
  - Test-FasUserCertificateCrypto: Test-FasUserCertificateCrypto.md
  - Unpublish-FasMsTemplate: Unpublish-FasMsTemplate.md